In [1]:
import pandas as pd
from sklearn.utils import resample

In [31]:
df=pd.DataFrame({
    'Age':[22,25,27,28,30,35,40,45,50,55,60,65,70],
    'Income':[2000,2500,2700,3200,3500,3800,4000,4200,4300,4500,5000,5500,6000],
    'Class':['High','Low','Low','High','High','Low','High','High','Low','Low','High','High','Low']
})

In [32]:
df_high = df[df["Class"]=="High"]
df_low = df[df["Class"]=="Low"]

In [33]:
df_high_downsampled = resample(df_high,replace=False,n_samples=len(df_low),random_state=50)
df_high_downsampled

    Age  Income Class
4    30    3500  High
10   60    5000  High
7    45    4200  High
3    28    3200  High
6    40    4000  High
11   65    5500  High

In [56]:
df_low_upsampled = resample(df_low,replace=True,n_samples=len(df_high))
df_low_upsampled

    Age  Income Class
8    50    4300   Low
2    27    2700   Low
1    25    2500   Low
12   70    6000   Low
5    35    3800   Low
12   70    6000   Low
2    27    2700   Low

In [59]:
df_resampled = pd.concat([df_high_downsampled,df_low])
df_resampled

    Age  Income Class
4    30    3500  High
10   60    5000  High
7    45    4200  High
3    28    3200  High
6    40    4000  High
11   65    5500  High
1    25    2500   Low
2    27    2700   Low
5    35    3800   Low
8    50    4300   Low
9    55    4500   Low
12   70    6000   Low

In [60]:
df_resampled_1 = pd.concat([df_low_upsampled,df_high])
df_resampled_1

    Age  Income Class
8    50    4300   Low
2    27    2700   Low
1    25    2500   Low
12   70    6000   Low
5    35    3800   Low
12   70    6000   Low
2    27    2700   Low
0    22    2000  High
3    28    3200  High
4    30    3500  High
6    40    4000  High
7    45    4200  High
10   60    5000  High
11   65    5500  High

## SMOTE
   - SMOTE to generate synthetic samples instead of duplicating existing ones. 
   - Convert categorical class labels into numeric form for SMOTE to work. 
   - Apply SMOTE to balance the dataset. 
   - Convert back to original categorical labels. 
   - Combine the resampled data into a final balanced dataset.
   - To import `from imblearn.over_sampling import SMOTE`

^C

In [65]:
from imblearn.over_sampling import SMOTE

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\CVR\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py)